/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseListByCategoryDetailResponseData
 */
public class ExpenseListByCategoryDetailResponseDataTest {
    private final ExpenseListByCategoryDetailResponseData model = new ExpenseListByCategoryDetailResponseData();

    /**
     * Model tests for ExpenseListByCategoryDetailResponseData
     */
    @Test
    public void testExpenseListByCategoryDetailResponseData() {
        // TODO: test ExpenseListByCategoryDetailResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'wayOfInput'
     */
    @Test
    public void wayOfInputTest() {
        // TODO: test wayOfInput
    }

    /**
     * Test the property 'pricePerKilometer'
     */
    @Test
    public void pricePerKilometerTest() {
        // TODO: test pricePerKilometer
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'payrollComponents'
     */
    @Test
    public void payrollComponentsTest() {
        // TODO: test payrollComponents
    }

}
