/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ExpenseListByYearResponseDataInner
 */
public class ExpenseListByYearResponseDataInnerTest {
    private final ExpenseListByYearResponseDataInner model = new ExpenseListByYearResponseDataInner();

    /**
     * Model tests for ExpenseListByYearResponseDataInner
     */
    @Test
    public void testExpenseListByYearResponseDataInner() {
        // TODO: test ExpenseListByYearResponseDataInner
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'timeCreated'
     */
    @Test
    public void timeCreatedTest() {
        // TODO: test timeCreated
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'payoutMethod'
     */
    @Test
    public void payoutMethodTest() {
        // TODO: test payoutMethod
    }

    /**
     * Test the property 'payoutPeriod'
     */
    @Test
    public void payoutPeriodTest() {
        // TODO: test payoutPeriod
    }

    /**
     * Test the property 'payoutPeriodFrequency'
     */
    @Test
    public void payoutPeriodFrequencyTest() {
        // TODO: test payoutPeriodFrequency
    }

    /**
     * Test the property 'payoutYear'
     */
    @Test
    public void payoutYearTest() {
        // TODO: test payoutYear
    }

    /**
     * Test the property 'expenseCategoryId'
     */
    @Test
    public void expenseCategoryIdTest() {
        // TODO: test expenseCategoryId
    }

    /**
     * Test the property 'pricePerKilometer'
     */
    @Test
    public void pricePerKilometerTest() {
        // TODO: test pricePerKilometer
    }

    /**
     * Test the property 'distance'
     */
    @Test
    public void distanceTest() {
        // TODO: test distance
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'dateApproved'
     */
    @Test
    public void dateApprovedTest() {
        // TODO: test dateApproved
    }

    /**
     * Test the property 'payoutOtherReason'
     */
    @Test
    public void payoutOtherReasonTest() {
        // TODO: test payoutOtherReason
    }

    /**
     * Test the property 'payoutStatus'
     */
    @Test
    public void payoutStatusTest() {
        // TODO: test payoutStatus
    }

}
