/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonGetDetailResponseDataCustomFieldsInner
 */
public class PersonGetDetailResponseDataCustomFieldsInnerTest {
    private final PersonGetDetailResponseDataCustomFieldsInner model = new PersonGetDetailResponseDataCustomFieldsInner();

    /**
     * Model tests for PersonGetDetailResponseDataCustomFieldsInner
     */
    @Test
    public void testPersonGetDetailResponseDataCustomFieldsInner() {
        // TODO: test PersonGetDetailResponseDataCustomFieldsInner
    }

    /**
     * Test the property 'customFieldId'
     */
    @Test
    public void customFieldIdTest() {
        // TODO: test customFieldId
    }

    /**
     * Test the property 'customFieldName'
     */
    @Test
    public void customFieldNameTest() {
        // TODO: test customFieldName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'valueName'
     */
    @Test
    public void valueNameTest() {
        // TODO: test valueName
    }

}
