/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PersonGetCurrentWageResponseDataCustomPayrollData;
import com.konfigthis.client.model.PersonGetCurrentWageResponseDataEstimatedMonthlyCost;
import com.konfigthis.client.model.PersonGetCurrentWageResponseDataMultipleWeekSchedule;
import com.konfigthis.client.model.PersonGetCurrentWageResponseDataWeeklyTimeEngagementMinutes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonGetCurrentWageResponseData
 */
public class PersonGetCurrentWageResponseDataTest {
    private final PersonGetCurrentWageResponseData model = new PersonGetCurrentWageResponseData();

    /**
     * Model tests for PersonGetCurrentWageResponseData
     */
    @Test
    public void testPersonGetCurrentWageResponseData() {
        // TODO: test PersonGetCurrentWageResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'estimatedMonthlyTotal'
     */
    @Test
    public void estimatedMonthlyTotalTest() {
        // TODO: test estimatedMonthlyTotal
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'rate'
     */
    @Test
    public void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'registrationCountryCode'
     */
    @Test
    public void registrationCountryCodeTest() {
        // TODO: test registrationCountryCode
    }

    /**
     * Test the property 'estimatedMonthlyCost'
     */
    @Test
    public void estimatedMonthlyCostTest() {
        // TODO: test estimatedMonthlyCost
    }

    /**
     * Test the property 'weeklyTimeEngagementMinutes'
     */
    @Test
    public void weeklyTimeEngagementMinutesTest() {
        // TODO: test weeklyTimeEngagementMinutes
    }

    /**
     * Test the property 'customPayrollData'
     */
    @Test
    public void customPayrollDataTest() {
        // TODO: test customPayrollData
    }

    /**
     * Test the property 'terminationReason'
     */
    @Test
    public void terminationReasonTest() {
        // TODO: test terminationReason
    }

    /**
     * Test the property 'multipleWeekSchedule'
     */
    @Test
    public void multipleWeekScheduleTest() {
        // TODO: test multipleWeekSchedule
    }

    /**
     * Test the property 'contractIndexNumber'
     */
    @Test
    public void contractIndexNumberTest() {
        // TODO: test contractIndexNumber
    }

}
