/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonListPeopleResponseDataInner
 */
public class PersonListPeopleResponseDataInnerTest {
    private final PersonListPeopleResponseDataInner model = new PersonListPeopleResponseDataInner();

    /**
     * Model tests for PersonListPeopleResponseDataInner
     */
    @Test
    public void testPersonListPeopleResponseDataInner() {
        // TODO: test PersonListPeopleResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'roleName'
     */
    @Test
    public void roleNameTest() {
        // TODO: test roleName
    }

    /**
     * Test the property 'archived'
     */
    @Test
    public void archivedTest() {
        // TODO: test archived
    }

    /**
     * Test the property 'linkedPayrollProviderExternalId'
     */
    @Test
    public void linkedPayrollProviderExternalIdTest() {
        // TODO: test linkedPayrollProviderExternalId
    }

    /**
     * Test the property 'payrollProvider'
     */
    @Test
    public void payrollProviderTest() {
        // TODO: test payrollProvider
    }

    /**
     * Test the property 'linkedIntegrationAlias'
     */
    @Test
    public void linkedIntegrationAliasTest() {
        // TODO: test linkedIntegrationAlias
    }

}
