/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonGetVerzuimPeriodsResponseDataInnerInner
 */
public class PersonGetVerzuimPeriodsResponseDataInnerInnerTest {
    private final PersonGetVerzuimPeriodsResponseDataInnerInner model = new PersonGetVerzuimPeriodsResponseDataInnerInner();

    /**
     * Model tests for PersonGetVerzuimPeriodsResponseDataInnerInner
     */
    @Test
    public void testPersonGetVerzuimPeriodsResponseDataInnerInner() {
        // TODO: test PersonGetVerzuimPeriodsResponseDataInnerInner
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'durationType'
     */
    @Test
    public void durationTypeTest() {
        // TODO: test durationType
    }

    /**
     * Test the property 'durationMinutesOnFirstDay'
     */
    @Test
    public void durationMinutesOnFirstDayTest() {
        // TODO: test durationMinutesOnFirstDay
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
