/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PersonGetOneOffWageComponentsByMonthResponseComponentsInnerParts;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PersonGetOneOffWageComponentsByMonthResponseComponentsInner
 */
public class PersonGetOneOffWageComponentsByMonthResponseComponentsInnerTest {
    private final PersonGetOneOffWageComponentsByMonthResponseComponentsInner model = new PersonGetOneOffWageComponentsByMonthResponseComponentsInner();

    /**
     * Model tests for PersonGetOneOffWageComponentsByMonthResponseComponentsInner
     */
    @Test
    public void testPersonGetOneOffWageComponentsByMonthResponseComponentsInner() {
        // TODO: test PersonGetOneOffWageComponentsByMonthResponseComponentsInner
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'inputType'
     */
    @Test
    public void inputTypeTest() {
        // TODO: test inputType
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

    /**
     * Test the property 'estimateTotal'
     */
    @Test
    public void estimateTotalTest() {
        // TODO: test estimateTotal
    }

    /**
     * Test the property 'parts'
     */
    @Test
    public void partsTest() {
        // TODO: test parts
    }

    /**
     * Test the property 'customPayrollData'
     */
    @Test
    public void customPayrollDataTest() {
        // TODO: test customPayrollData
    }

}
