/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VehicleGetDetailResponseDataCustomFieldsInner;
import com.konfigthis.client.model.VehicleGetDetailResponseDataOwner;
import com.konfigthis.client.model.VehicleGetDetailResponseDataYearlyCost;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VehicleGetDetailResponseData
 */
public class VehicleGetDetailResponseDataTest {
    private final VehicleGetDetailResponseData model = new VehicleGetDetailResponseData();

    /**
     * Model tests for VehicleGetDetailResponseData
     */
    @Test
    public void testVehicleGetDetailResponseData() {
        // TODO: test VehicleGetDetailResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'brand'
     */
    @Test
    public void brandTest() {
        // TODO: test brand
    }

    /**
     * Test the property 'model'
     */
    @Test
    public void modelTest() {
        // TODO: test model
    }

    /**
     * Test the property 'fuel'
     */
    @Test
    public void fuelTest() {
        // TODO: test fuel
    }

    /**
     * Test the property 'plate'
     */
    @Test
    public void plateTest() {
        // TODO: test plate
    }

    /**
     * Test the property 'hp'
     */
    @Test
    public void hpTest() {
        // TODO: test hp
    }

    /**
     * Test the property 'co2GKm'
     */
    @Test
    public void co2GKmTest() {
        // TODO: test co2GKm
    }

    /**
     * Test the property 'chassisNumber'
     */
    @Test
    public void chassisNumberTest() {
        // TODO: test chassisNumber
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'supplier'
     */
    @Test
    public void supplierTest() {
        // TODO: test supplier
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'catalogueValue'
     */
    @Test
    public void catalogueValueTest() {
        // TODO: test catalogueValue
    }

    /**
     * Test the property 'dateFirstRegistration'
     */
    @Test
    public void dateFirstRegistrationTest() {
        // TODO: test dateFirstRegistration
    }

    /**
     * Test the property 'specifics'
     */
    @Test
    public void specificsTest() {
        // TODO: test specifics
    }

    /**
     * Test the property 'yearlyCost'
     */
    @Test
    public void yearlyCostTest() {
        // TODO: test yearlyCost
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

}
