/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity;
import com.konfigthis.client.model.PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode;
import com.konfigthis.client.model.PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1;
import com.konfigthis.client.model.PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PersonGetPersonalDataChangesResponseLogsInnerChangedValues
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PersonGetPersonalDataChangesResponseLogsInnerChangedValues {
  public static final String SERIALIZED_NAME_ADDRESS_COUNTRY_CODE = "address_country_code";
  @SerializedName(SERIALIZED_NAME_ADDRESS_COUNTRY_CODE)
  private PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode addressCountryCode;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "address_line_1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1 addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_ZIPCODE = "address_zipcode";
  @SerializedName(SERIALIZED_NAME_ADDRESS_ZIPCODE)
  private PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode addressZipcode;

  public static final String SERIALIZED_NAME_ADDRESS_CITY = "address_city";
  @SerializedName(SERIALIZED_NAME_ADDRESS_CITY)
  private PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity addressCity;

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues() {
  }

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues addressCountryCode(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode addressCountryCode) {
    
    
    
    
    this.addressCountryCode = addressCountryCode;
    return this;
  }

   /**
   * Get addressCountryCode
   * @return addressCountryCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode getAddressCountryCode() {
    return addressCountryCode;
  }


  public void setAddressCountryCode(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode addressCountryCode) {
    
    
    
    this.addressCountryCode = addressCountryCode;
  }


  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues addressLine1(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1 addressLine1) {
    
    
    
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Get addressLine1
   * @return addressLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1 getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1 addressLine1) {
    
    
    
    this.addressLine1 = addressLine1;
  }


  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues addressZipcode(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode addressZipcode) {
    
    
    
    
    this.addressZipcode = addressZipcode;
    return this;
  }

   /**
   * Get addressZipcode
   * @return addressZipcode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode getAddressZipcode() {
    return addressZipcode;
  }


  public void setAddressZipcode(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode addressZipcode) {
    
    
    
    this.addressZipcode = addressZipcode;
  }


  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues addressCity(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity addressCity) {
    
    
    
    
    this.addressCity = addressCity;
    return this;
  }

   /**
   * Get addressCity
   * @return addressCity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity getAddressCity() {
    return addressCity;
  }


  public void setAddressCity(PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity addressCity) {
    
    
    
    this.addressCity = addressCity;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PersonGetPersonalDataChangesResponseLogsInnerChangedValues instance itself
   */
  public PersonGetPersonalDataChangesResponseLogsInnerChangedValues putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonGetPersonalDataChangesResponseLogsInnerChangedValues personGetPersonalDataChangesResponseLogsInnerChangedValues = (PersonGetPersonalDataChangesResponseLogsInnerChangedValues) o;
    return Objects.equals(this.addressCountryCode, personGetPersonalDataChangesResponseLogsInnerChangedValues.addressCountryCode) &&
        Objects.equals(this.addressLine1, personGetPersonalDataChangesResponseLogsInnerChangedValues.addressLine1) &&
        Objects.equals(this.addressZipcode, personGetPersonalDataChangesResponseLogsInnerChangedValues.addressZipcode) &&
        Objects.equals(this.addressCity, personGetPersonalDataChangesResponseLogsInnerChangedValues.addressCity)&&
        Objects.equals(this.additionalProperties, personGetPersonalDataChangesResponseLogsInnerChangedValues.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressCountryCode, addressLine1, addressZipcode, addressCity, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonGetPersonalDataChangesResponseLogsInnerChangedValues {\n");
    sb.append("    addressCountryCode: ").append(toIndentedString(addressCountryCode)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressZipcode: ").append(toIndentedString(addressZipcode)).append("\n");
    sb.append("    addressCity: ").append(toIndentedString(addressCity)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("address_country_code");
    openapiFields.add("address_line_1");
    openapiFields.add("address_zipcode");
    openapiFields.add("address_city");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PersonGetPersonalDataChangesResponseLogsInnerChangedValues
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PersonGetPersonalDataChangesResponseLogsInnerChangedValues.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PersonGetPersonalDataChangesResponseLogsInnerChangedValues is not found in the empty JSON string", PersonGetPersonalDataChangesResponseLogsInnerChangedValues.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `address_country_code`
      if (jsonObj.get("address_country_code") != null && !jsonObj.get("address_country_code").isJsonNull()) {
        PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCountryCode.validateJsonObject(jsonObj.getAsJsonObject("address_country_code"));
      }
      // validate the optional field `address_line_1`
      if (jsonObj.get("address_line_1") != null && !jsonObj.get("address_line_1").isJsonNull()) {
        PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressLine1.validateJsonObject(jsonObj.getAsJsonObject("address_line_1"));
      }
      // validate the optional field `address_zipcode`
      if (jsonObj.get("address_zipcode") != null && !jsonObj.get("address_zipcode").isJsonNull()) {
        PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressZipcode.validateJsonObject(jsonObj.getAsJsonObject("address_zipcode"));
      }
      // validate the optional field `address_city`
      if (jsonObj.get("address_city") != null && !jsonObj.get("address_city").isJsonNull()) {
        PersonGetPersonalDataChangesResponseLogsInnerChangedValuesAddressCity.validateJsonObject(jsonObj.getAsJsonObject("address_city"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PersonGetPersonalDataChangesResponseLogsInnerChangedValues.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PersonGetPersonalDataChangesResponseLogsInnerChangedValues' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PersonGetPersonalDataChangesResponseLogsInnerChangedValues> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PersonGetPersonalDataChangesResponseLogsInnerChangedValues.class));

       return (TypeAdapter<T>) new TypeAdapter<PersonGetPersonalDataChangesResponseLogsInnerChangedValues>() {
           @Override
           public void write(JsonWriter out, PersonGetPersonalDataChangesResponseLogsInnerChangedValues value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PersonGetPersonalDataChangesResponseLogsInnerChangedValues read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PersonGetPersonalDataChangesResponseLogsInnerChangedValues instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PersonGetPersonalDataChangesResponseLogsInnerChangedValues given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PersonGetPersonalDataChangesResponseLogsInnerChangedValues
  * @throws IOException if the JSON string is invalid with respect to PersonGetPersonalDataChangesResponseLogsInnerChangedValues
  */
  public static PersonGetPersonalDataChangesResponseLogsInnerChangedValues fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PersonGetPersonalDataChangesResponseLogsInnerChangedValues.class);
  }

 /**
  * Convert an instance of PersonGetPersonalDataChangesResponseLogsInnerChangedValues to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

