/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ComponentGrantOneOffWageResponse;
import com.konfigthis.client.model.ComponentRemoveOneOffWageResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComponentApi
 */
@Disabled
public class ComponentApiTest {

    private static ComponentApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ComponentApi(apiClient);
    }

    /**
     * Grant one-off wage component
     *
     * Grants a one-off wage components for a specific person, in a specific month
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void grantOneOffWageTest() throws ApiException {
        ComponentGrantOneOffWageResponse response = api.grantOneOffWage()
                .execute();
        // TODO: test validations
    }

    /**
     * Remove one-off wage component
     *
     * Removes a one-off wage component for a specific person in a specific month, by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeOneOffWageTest() throws ApiException {
        ComponentRemoveOneOffWageResponse response = api.removeOneOffWage()
                .execute();
        // TODO: test validations
    }

}
