/*
 * Officient API
 * Officient offers an intuitive HRIS which helps manage all personnel administration through our HR platform & personalized employee self-services. Manage payroll, company assets, contracts, days off, fleet, performance reviews and all employee data in one HR system. HR deserves great software and we're here to provide it.  We support our customers in transforming HR towards paperless administration and automating tedious workforce management tasks in the process. Our goal? Transform HR from an administrative, processing role, to a controlling role which fuels HR strategy across the organization.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ContractCreateNewContractResponse;
import com.konfigthis.client.model.ContractGetAllResponse;
import com.konfigthis.client.model.ContractGetPdfLinkResponse;
import com.konfigthis.client.model.ContractRequestSignatureResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContractApi
 */
@Disabled
public class ContractApiTest {

    private static ContractApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ContractApi(apiClient);
    }

    /**
     * Add contract
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewContractTest() throws ApiException {
        ContractCreateNewContractResponse response = api.createNewContract()
                .execute();
        // TODO: test validations
    }

    /**
     * List contracts
     *
     * Get a list of all contracts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        Integer page = null;
        ContractGetAllResponse response = api.getAll(page)
                .execute();
        // TODO: test validations
    }

    /**
     * Contract detail
     *
     * Get details about one contract
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailTest() throws ApiException {
        Integer contractId = null;
        String response = api.getDetail(contractId)
                .execute();
        // TODO: test validations
    }

    /**
     * Contract PDF
     *
     * Get a PDF download link for any contract
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getPdfLinkTest() throws ApiException {
        Integer contractId = null;
        ContractGetPdfLinkResponse response = api.getPdfLink(contractId)
                .execute();
        // TODO: test validations
    }

    /**
     * Request contract signature
     *
     * This API sends out an email invite requesting to sign a contract
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void requestSignatureTest() throws ApiException {
        ContractRequestSignatureResponse response = api.requestSignature()
                .execute();
        // TODO: test validations
    }

}
